'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';

type Project={id:string;name:string;municipality?:string|null};
type Site={id:string;project_id:string;name:string;site_code?:string|null;area_name?:string|null;status:string;created_at:string;updated_at:string;source_system?:string|null;source_code?:string|null;source_district?:string|null;synced_at?:string|null;work_orders_count:number;items_count:number;total_remaining_quantity:number;last_work_order_date:string|null;project:Project|null};
type Form={name:string;project_id:string;site_code:string;area_name:string;status:string};
const emptyForm:Form={name:'',project_id:'',site_code:'',area_name:'',status:'active'};
const fmt=(value:unknown)=>Number(value||0).toLocaleString('ar-SA',{maximumFractionDigits:2});
const statusLabel=(status:string)=>status==='inactive'?'متوقف':status==='completed'?'مكتمل':'نشط';

function SiteActionIcon({name}:{name:'edit'|'story'|'orders'|'pause'|'play'|'delete'}){
 const common={width:19,height:19,viewBox:'0 0 24 24',fill:'none',stroke:'currentColor',strokeWidth:1.9,strokeLinecap:'round' as const,strokeLinejoin:'round' as const,'aria-hidden':true};
 if(name==='edit')return <svg {...common}><path d="M12 20h9"/><path d="M16.5 3.5a2.12 2.12 0 0 1 3 3L8 18l-4 1 1-4Z"/></svg>;
 if(name==='story')return <svg {...common}><path d="M12 21s7-4.35 7-11a7 7 0 1 0-14 0c0 6.65 7 11 7 11Z"/><circle cx="12" cy="10" r="2.4"/></svg>;
 if(name==='orders')return <svg {...common}><rect x="5" y="3" width="14" height="18" rx="2"/><path d="M9 7h6M9 11h6M9 15h4"/></svg>;
 if(name==='play')return <svg {...common}><circle cx="12" cy="12" r="9"/><path d="m10 8 6 4-6 4Z"/></svg>;
 if(name==='pause')return <svg {...common}><circle cx="12" cy="12" r="9"/><path d="M10 9v6M14 9v6"/></svg>;
 return <svg {...common}><path d="M3 6h18"/><path d="M8 6V4h8v2M19 6l-1 14H6L5 6"/><path d="M10 11v5M14 11v5"/></svg>;
}

export default function SitesPage(){
 const [sites,setSites]=useState<Site[]>([]); const [projects,setProjects]=useState<Project[]>([]); const [loading,setLoading]=useState(true);
 const [query,setQuery]=useState(''); const [projectFilter,setProjectFilter]=useState('all'); const [statusFilter,setStatusFilter]=useState('all'); const [sort,setSort]=useState('name');
 const [modal,setModal]=useState<'create'|'edit'|'delete'|null>(null); const [selected,setSelected]=useState<Site|null>(null); const [form,setForm]=useState<Form>(emptyForm); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(''); const [menuId,setMenuId]=useState('');
 useEffect(()=>{void load();},[]);
 useEffect(()=>{
  if(!modal)return;
  const previousOverflow=document.body.style.overflow;
  document.body.style.overflow='hidden';
  const onKeyDown=(event:KeyboardEvent)=>{if(event.key==='Escape'&&!busy)setModal(null);};
  window.addEventListener('keydown',onKeyDown);
  return ()=>{document.body.style.overflow=previousOverflow;window.removeEventListener('keydown',onKeyDown);};
 },[modal,busy]);
 async function load(){setLoading(true);try{const response=await fetch('/api/sites',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر تحميل المواقع.');setSites(data.sites||[]);setProjects(data.projects||[]);}catch(error){setMessage(error instanceof Error?error.message:'تعذر تحميل المواقع.');}finally{setLoading(false);}}
 const stats=useMemo(()=>({total:sites.length,active:sites.filter(s=>s.status==='active').length,inactive:sites.filter(s=>s.status==='inactive').length,completed:sites.filter(s=>s.status==='completed').length,linked:sites.filter(s=>s.work_orders_count>0).length,unlinked:sites.filter(s=>s.work_orders_count===0).length}),[sites]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return [...sites].filter(site=>{const hay=`${site.name} ${site.site_code||''} ${site.area_name||''} ${site.project?.name||''} ${site.project?.municipality||''}`.toLowerCase();return (!q||hay.includes(q))&&(projectFilter==='all'||site.project_id===projectFilter)&&(statusFilter==='all'||site.status===statusFilter);}).sort((a,b)=>sort==='latest'?new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime():sort==='orders'?b.work_orders_count-a.work_orders_count:a.name.localeCompare(b.name,'ar'));},[sites,query,projectFilter,statusFilter,sort]);
 function openCreate(){setSelected(null);setForm({...emptyForm,project_id:projectFilter!=='all'?projectFilter:(projects[0]?.id||'')});setModal('create');setMessage('');}
 function openEdit(site:Site){setSelected(site);setForm({name:site.name,project_id:site.project_id,site_code:site.site_code||site.source_code||'',area_name:site.area_name||site.source_district||'',status:site.status});setModal('edit');setMenuId('');setMessage('');}
 async function save(){if(!form.name.trim()||!form.project_id){setMessage('اسم الموقع والمشروع مطلوبان.');return;}setBusy(true);setMessage('');try{const response=await fetch(modal==='edit'&&selected?`/api/sites/${selected.id}`:'/api/sites',{method:modal==='edit'?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر حفظ الموقع.');setModal(null);setMessage(modal==='edit'?'تم تحديث الموقع بنجاح.':'تم إنشاء الموقع بنجاح.');await load();}catch(error){setMessage(error instanceof Error?error.message:'تعذر حفظ الموقع.');}finally{setBusy(false);}}
 async function remove(){if(!selected)return;setBusy(true);setMessage('');try{const response=await fetch(`/api/sites/${selected.id}`,{method:'DELETE'});const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر حذف الموقع.');setModal(null);setMessage('تم حذف الموقع بنجاح.');await load();}catch(error){setMessage(error instanceof Error?error.message:'تعذر حذف الموقع.');}finally{setBusy(false);}}
 async function quickStatus(site:Site,status:string){setBusy(true);try{const response=await fetch(`/api/sites/${site.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});const data=await response.json();if(!response.ok)throw new Error(data.error);setMessage(status==='inactive'?'تم إيقاف الموقع.':'تم تفعيل الموقع.');await load();}catch(error){setMessage(error instanceof Error?error.message:'تعذر تحديث الحالة.');}finally{setBusy(false);setMenuId('');}}
 return <main className="page sites-management-page">
  <section className="sites-hero"><div><span className="eyebrow">إدارة المواقع</span><h1>مركز إدارة المواقع التشغيلية</h1><p>راقب المواقع واربطها بالمشاريع وأوامر العمل، وتابع حالة كل موقع وسجله التشغيلي من مكان واحد.</p></div><div className="sites-hero-actions"><button className="btn primary" onClick={openCreate}>+ موقع جديد</button></div></section>
  {message?<div className="integration-message sites-message">{message}</div>:null}
  <section className="stats sites-stats"><div className="stat"><small>إجمالي المواقع</small><strong>{stats.total}</strong><span>موقع مسجل</span></div><div className="stat"><small>نشطة</small><strong>{stats.active}</strong><span>متاحة للتشغيل</span></div><div className="stat warning"><small>متوقفة</small><strong>{stats.inactive}</strong><span>تحتاج متابعة</span></div><div className="stat"><small>مرتبطة بأوامر</small><strong>{stats.linked}</strong><span>لها سجل تشغيلي</span></div><div className="stat muted"><small>بدون أمر عمل</small><strong>{stats.unlinked}</strong><span>لم تدخل التنفيذ</span></div></section>
  <section className="section-block"><div className="section-title"><div><span className="eyebrow">النتائج</span><h2>دليل المواقع</h2></div><small>{filtered.length} من {sites.length} موقع</small></div>
   {loading?<div className="sites-skeleton-grid">{Array.from({length:6}).map((_,i)=><div className="site-skeleton" key={i}/>)}</div>:filtered.length===0?<div className="sites-empty"><div className="sites-empty-icon">⌖</div><h3>لا توجد مواقع مطابقة</h3><p>غيّر الفلاتر أو أضف موقعًا جديدًا للمشروع.</p><button className="btn primary" onClick={openCreate}>إضافة موقع</button></div>:<div className="sites-card-grid">{filtered.map((site,index)=><article className="site-management-card" key={site.id} data-status={site.status}><div className="site-card-head"><div><span className={`site-status ${site.status}`}>{statusLabel(site.status)}</span><small>{site.source_system==='irrigation'?'متزامن من نظام الري':'إدخال النظام'}</small></div><div className="site-menu-wrap"><button className="icon-menu-btn" onClick={()=>setMenuId(menuId===site.id?'':site.id)}>⋮</button>{menuId===site.id?<div className="site-actions-menu" role="menu"><div className="site-menu-group"><button onClick={()=>openEdit(site)}><SiteActionIcon name="edit"/><span>تعديل الموقع</span></button><Link href={`/site/${site.id}`}><SiteActionIcon name="story"/><span>فتح قصة الموقع</span></Link><Link href={`/work-orders?site=${site.id}`}><SiteActionIcon name="orders"/><span>أوامر العمل المرتبطة</span></Link><button onClick={()=>void quickStatus(site,site.status==='inactive'?'active':'inactive')}><SiteActionIcon name={site.status==='inactive'?'play':'pause'}/><span>{site.status==='inactive'?'تفعيل الموقع':'إيقاف الموقع'}</span></button></div><div className="site-menu-divider"/><div className="site-menu-group danger-group"><button className="danger" onClick={()=>{setSelected(site);setModal('delete');setMenuId('');}}><SiteActionIcon name="delete"/><span>حذف الموقع</span></button></div></div>:null}</div></div><div className="site-identity-row"><span className="site-identity-badge">{site.site_code||site.source_code||`الموقع ${String(index+1).padStart(2,'0')}`}</span></div><div className="site-card-title"><span className="site-pin">⌖</span><div><h3>{site.name}</h3><p>{site.project?.name||'مشروع غير محدد'}</p></div></div><div className="site-meta-line"><span><small>البلدية / النطاق</small><b>{site.area_name||site.source_district||site.project?.municipality||'غير مسجل'}</b></span><span><small>رمز الموقع</small><b>{site.site_code||site.source_code||'—'}</b></span></div><div className="site-card-metrics"><span><small>أوامر العمل</small><b>{site.work_orders_count}</b></span><span><small>البنود</small><b>{site.items_count}</b></span><span><small>الرصيد المتبقي</small><b>{fmt(site.total_remaining_quantity)}</b></span></div><div className="site-last-activity"><small>آخر أمر عمل</small><b>{site.last_work_order_date||'لا يوجد'}</b></div><Link className="site-primary-action" href={`/site/${site.id}`}>فتح الموقع</Link></article>)}</div>}
  </section>
  {modal?createPortal(<div className="site-modal-backdrop" role="presentation" onMouseDown={()=>!busy&&setModal(null)}><section className="site-modal" role="dialog" aria-modal="true" aria-labelledby="site-modal-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" type="button" aria-label="إغلاق النافذة" onClick={()=>setModal(null)}>×</button>{modal==='delete'?<><span className="eyebrow">حذف موقع</span><h2 id="site-modal-title">تأكيد حذف الموقع</h2><p>سيتم حذف <b>{selected?.name}</b> نهائيًا إذا لم يكن مرتبطًا بأوامر عمل أو ملاحظات. للمواقع التشغيلية يُفضّل الإيقاف بدل الحذف.</p><div className="delete-site-summary"><span><small>أوامر العمل</small><b>{selected?.work_orders_count||0}</b></span><span><small>البنود</small><b>{selected?.items_count||0}</b></span></div><div className="modal-actions"><button className="btn danger-btn" disabled={busy} onClick={()=>void remove()}>{busy?'جاري الحذف...':'حذف الموقع'}</button><button className="btn" onClick={()=>setModal(null)}>إلغاء</button></div></>:<><span className="eyebrow">{modal==='create'?'إضافة موقع':'تعديل موقع'}</span><h2 id="site-modal-title">{modal==='create'?'موقع جديد':selected?.name}</h2><div className="site-form-grid"><label className="wide"><span>اسم الموقع *</span><input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>المشروع *</span><select value={form.project_id} onChange={e=>setForm({...form,project_id:e.target.value})}><option value="">اختر المشروع</option>{projects.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label><span>الحالة</span><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="active">نشط</option><option value="inactive">متوقف</option><option value="completed">مكتمل</option></select></label><label><span>رمز الموقع</span><input value={form.site_code} onChange={e=>setForm({...form,site_code:e.target.value})} placeholder="مثال: SITE-014"/></label><label><span>البلدية / النطاق</span><input value={form.area_name} onChange={e=>setForm({...form,area_name:e.target.value})}/></label></div><div className="modal-actions"><button className="btn primary" disabled={busy} onClick={()=>void save()}>{busy?'جاري الحفظ...':modal==='create'?'إنشاء الموقع':'حفظ التعديلات'}</button><button className="btn" onClick={()=>setModal(null)}>إلغاء</button></div></>}</section></div>,document.body):null}
 </main>;
}
