import { NextRequest, NextResponse } from 'next/server';
import { createWorkOrdersAdminClient } from '@/lib/server-supabase';
export const dynamic = 'force-dynamic';
type Context={params:{siteId:string}};
function clean(value: unknown){const text=String(value??'').trim();return text||null;}
function normalizeArabic(value:string){return value.normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/[^\p{L}\p{N}]+/gu,' ').trim().toLowerCase();}
function message(error:unknown,fallback:string){const e=error&&typeof error==='object'?error as {message?:string;details?:string;hint?:string;code?:string}:null;return [e?.message,e?.details,e?.hint,e?.code?`الرمز: ${e.code}`:null].filter(Boolean).join(' — ')||fallback;}
export async function PATCH(request:NextRequest,{params}:Context){try{const body=await request.json();const payload:Record<string,unknown>={};if(body.name!==undefined){const name=String(body.name||'').trim();if(!name)return NextResponse.json({error:'اسم الموقع مطلوب.'},{status:400});payload.name=name;payload.normalized_name=normalizeArabic(name);}if(body.project_id!==undefined)payload.project_id=String(body.project_id);if(body.site_code!==undefined)payload.site_code=clean(body.site_code);if(body.area_name!==undefined)payload.area_name=clean(body.area_name);if(body.status!==undefined)payload.status=clean(body.status)||'active';const work=createWorkOrdersAdminClient();const result=await work.from('sites').update(payload).eq('id',params.siteId).select('id,project_id,name,site_code,area_name,status,created_at,updated_at,source_system,source_code,source_district,synced_at').single();if(result.error)throw result.error;return NextResponse.json({site:result.data});}catch(error){return NextResponse.json({error:message(error,'تعذر تعديل الموقع.')},{status:500});}}
export async function DELETE(_request:NextRequest,{params}:Context){try{const work=createWorkOrdersAdminClient();const [links,notes,profiles]=await Promise.all([work.from('work_order_sites').select('id',{count:'exact',head:true}).eq('site_id',params.siteId),work.from('site_notes').select('id',{count:'exact',head:true}).eq('site_id',params.siteId),work.from('site_profiles').select('id',{count:'exact',head:true}).eq('site_id',params.siteId)]);const error=links.error||notes.error||profiles.error;if(error)throw error;const dependencies={workOrders:links.count||0,notes:notes.count||0,profiles:profiles.count||0};if(dependencies.workOrders||dependencies.notes)return NextResponse.json({error:'لا يمكن حذف الموقع لوجود أوامر عمل أو ملاحظات مرتبطة به. عطّل الموقع بدلًا من الحذف.',dependencies},{status:409});if(dependencies.profiles){const p=await work.from('site_profiles').delete().eq('site_id',params.siteId);if(p.error)throw p.error;}const result=await work.from('sites').delete().eq('id',params.siteId);if(result.error)throw result.error;return NextResponse.json({deleted:true});}catch(error){return NextResponse.json({error:message(error,'تعذر حذف الموقع.')},{status:500});}}
