'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { isSupabaseConfigured, supabase } from '@/lib/supabase';
import { getWorkOrderTiming } from '@/lib/work-order-timing';

type Severity='critical'|'warning'|'info';
type Category='timing'|'data'|'import';
type Alert={id:string;severity:Severity;category:Category;title:string;description:string;meta:string;href:string;action:string;date:string|null};
type Order={id:string;work_order_number:string;title:string|null;status:string|null;work_order_date:string|null;work_order_end_date:string|null;duration_days:number|null;projects:{name:string}|null};
type ImportBatch={id:string;file_name:string;import_status:string;imported_rows_count:number|null;error_rows_count:number|null;notes:string|null;created_at:string};

const severityLabel:Record<Severity,string>={critical:'عاجل',warning:'تحذير',info:'تنبيه'};
const categoryLabel:Record<Category,string>={timing:'المواعيد',data:'جودة البيانات',import:'الاستيراد'};
const icon:Record<Category,string>={timing:'◷',data:'◇',import:'⇧'};
const fmt=(value:string|null)=>value?new Intl.DateTimeFormat('ar-SA',{year:'numeric',month:'short',day:'numeric'}).format(new Date(`${value.slice(0,10)}T00:00:00`)):'غير محدد';

export default function AlertsPage(){
 const [orders,setOrders]=useState<Order[]>([]),[imports,setImports]=useState<ImportBatch[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const [query,setQuery]=useState(''),[severity,setSeverity]=useState<'all'|Severity>('all'),[category,setCategory]=useState<'all'|Category>('all'),[reviewed,setReviewed]=useState<Set<string>>(new Set()),[showReviewed,setShowReviewed]=useState(false);
 const [visibleCount,setVisibleCount]=useState(8);
 useEffect(()=>{try{setReviewed(new Set(JSON.parse(localStorage.getItem('work-orders-reviewed-alerts')||'[]')))}catch{} void load()},[]);
 async function load(){if(!isSupabaseConfigured){setLoading(false);return}setLoading(true);setError('');const [ordersResult,importsResult]=await Promise.all([supabase.from('work_orders').select('id,work_order_number,title,status,work_order_date,work_order_end_date,duration_days,projects(name)').order('work_order_end_date',{ascending:true,nullsFirst:false}),supabase.from('import_batches').select('id,file_name,import_status,imported_rows_count,error_rows_count,notes,created_at').order('created_at',{ascending:false}).limit(100)]);const first=ordersResult.error||importsResult.error;if(first)setError(first.message);setOrders((ordersResult.data||[]) as unknown as Order[]);setImports((importsResult.data||[]) as ImportBatch[]);setLoading(false)}
 const alerts=useMemo(()=>{const result:Alert[]=[];for(const order of orders){const status=String(order.status||'approved').toLowerCase();if(status==='cancelled')continue;const name=order.title||`أمر عمل رقم ${order.work_order_number}`,project=order.projects?.name||'مشروع غير محدد',timing=getWorkOrderTiming(order.work_order_date,order.work_order_end_date);if(!order.work_order_date||!order.work_order_end_date){result.push({id:`data-${order.id}`,severity:'warning',category:'data',title:`بيانات زمنية ناقصة — ${name}`,description:!order.work_order_date&&!order.work_order_end_date?'تاريخ البداية والنهاية غير مسجلين.':!order.work_order_date?'تاريخ بداية أمر العمل غير مسجل.':'تاريخ نهاية أمر العمل غير مسجل.',meta:project,href:`/work-order/${order.id}`,action:'مراجعة الأمر',date:order.work_order_date||order.work_order_end_date});continue}if(timing.phase==='ended'&&status!=='completed'){result.push({id:`overdue-${order.id}`,severity:'critical',category:'timing',title:`أمر عمل متأخر — ${name}`,description:`انتهت المدة منذ ${Math.abs(timing.days||0)} يوم وما زالت حالته غير مكتملة.`,meta:`${project} · انتهى ${fmt(order.work_order_end_date)}`,href:`/work-order/${order.id}`,action:'فتح الأمر',date:order.work_order_end_date})}else if(timing.phase==='active'&&(timing.days??999)>0&&(timing.days??999)<=30){result.push({id:`ending-${order.id}`,severity:(timing.days??99)<=7?'critical':'warning',category:'timing',title:`موعد انتهاء قريب — ${name}`,description:`متبقي ${timing.days} يوم على نهاية أمر العمل.`,meta:`${project} · ينتهي ${fmt(order.work_order_end_date)}`,href:`/work-order/${order.id}`,action:'متابعة الأمر',date:order.work_order_end_date})}else if(timing.phase==='upcoming'&&(timing.days??999)<=30){result.push({id:`upcoming-${order.id}`,severity:'info',category:'timing',title:`أمر عمل سيبدأ قريبًا — ${name}`,description:`يبدأ خلال ${timing.days} يوم.`,meta:`${project} · يبدأ ${fmt(order.work_order_date)}`,href:`/work-order/${order.id}`,action:'عرض التفاصيل',date:order.work_order_date})}}
 for(const batch of imports){const failed=batch.import_status==='failed',errors=Number(batch.error_rows_count||0);if(failed||errors>0)result.push({id:`import-${batch.id}`,severity:failed?'critical':'warning',category:'import',title:failed?'فشل استيراد ملف Excel':'استيراد يحتوي سجلات تحتاج مراجعة',description:failed?(batch.notes||'لم تكتمل عملية الاستيراد.'): `اكتمل الاستيراد مع ${errors} سجل خطأ.`,meta:`${batch.file_name} · ${new Date(batch.created_at).toLocaleDateString('ar-SA')}`,href:'/import',action:'فتح الاستيراد',date:batch.created_at})}
 const weight:Record<Severity,number>={critical:3,warning:2,info:1};return result.sort((a,b)=>weight[b.severity]-weight[a.severity]||String(b.date||'').localeCompare(String(a.date||'')))},[orders,imports]);
 const counts=useMemo(()=>({total:alerts.length,critical:alerts.filter(a=>a.severity==='critical').length,warning:alerts.filter(a=>a.severity==='warning').length,info:alerts.filter(a=>a.severity==='info').length,unreviewed:alerts.filter(a=>!reviewed.has(a.id)).length}),[alerts,reviewed]);
 const filtered=useMemo(()=>alerts.filter(a=>(severity==='all'||a.severity===severity)&&(category==='all'||a.category===category)&&(showReviewed||!reviewed.has(a.id))&&(!query.trim()||`${a.title} ${a.description} ${a.meta}`.toLowerCase().includes(query.trim().toLowerCase()))),[alerts,severity,category,showReviewed,reviewed,query]);
 const visibleAlerts=filtered.slice(0,visibleCount);
 function toggleReviewed(id:string){setReviewed(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);localStorage.setItem('work-orders-reviewed-alerts',JSON.stringify([...next]));return next})}
 return <main className="page alerts-center-page">
  <section className="alerts-hero"><div><span className="eyebrow">المراقبة التشغيلية</span><h1>مركز التنبيهات</h1><p>نظرة موحّدة على المواعيد الحرجة، البيانات الناقصة، ونتائج الاستيراد التي تحتاج تدخلك.</p><div className="alerts-live"><i/> تحديث مباشر من قاعدة البيانات</div></div><div className="alerts-hero-score"><small>تحتاج مراجعة</small><strong>{counts.unreviewed}</strong><span>من أصل {counts.total} تنبيه</span></div></section>
  {!isSupabaseConfigured?<div className="notice">لم يتم ربط Supabase بالموقع.</div>:null}{error?<div className="notice error-notice">تعذر تحميل بعض التنبيهات: {error}</div>:null}
  <section className="alerts-summary"><div><small>جميع التنبيهات</small><strong>{counts.total}</strong><span>{counts.unreviewed} غير مراجع</span></div><div className="critical"><small>عاجلة</small><strong>{counts.critical}</strong><span>تحتاج إجراء سريعًا</span></div><div className="warning"><small>تحذيرات</small><strong>{counts.warning}</strong><span>تحتاج متابعة</span></div><div className="info"><small>معلومات</small><strong>{counts.info}</strong><span>للعلم والاستعداد</span></div></section>
  <section className="alerts-list-panel"><header><div><span className="section-kicker">قائمة الأولويات</span><h2>التنبيهات التي تحتاج انتباهك</h2></div><b>{filtered.length} نتيجة</b></header>{loading?<div className="alerts-skeleton">{[1,2,3].map(x=><span key={x}/>)}</div>:<><div className="alerts-list">{visibleAlerts.map(alert=><article className={`alert-center-card ${alert.severity} ${reviewed.has(alert.id)?'is-reviewed':''}`} key={alert.id}><div className="alert-category-icon">{icon[alert.category]}</div><div className="alert-card-main"><div className="alert-badges"><span className={`severity ${alert.severity}`}>{severityLabel[alert.severity]}</span><span>{categoryLabel[alert.category]}</span>{reviewed.has(alert.id)?<span className="reviewed">تمت المراجعة</span>:null}</div><h3>{alert.title}</h3><p>{alert.description}</p><small title={alert.meta}>{alert.meta}</small></div><div className="alert-card-actions"><Link href={alert.href}>{alert.action}</Link><button onClick={()=>toggleReviewed(alert.id)}>{reviewed.has(alert.id)?'إعادة للتنبيهات':'تحديد كمراجع'}</button></div></article>)}{!filtered.length?<div className="alerts-empty"><span>✓</span><h3>لا توجد تنبيهات مطابقة</h3><p>كل العناصر ضمن هذا النطاق تمت مراجعتها أو لا تحتاج إلى إجراء حاليًا.</p></div>:null}</div>{visibleCount<filtered.length?<button className="alerts-show-more" type="button" onClick={()=>setVisibleCount(count=>count+8)}>عرض المزيد <span>({filtered.length-visibleCount} متبقي)</span></button>:visibleCount>8&&filtered.length>8?<button className="alerts-show-more secondary" type="button" onClick={()=>setVisibleCount(8)}>عرض أول 8 تنبيهات</button>:null}</>}</section>
 </main>
}
