'use client';

import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';

type BasicProject={id:string;name:string;contractor_name?:string|null};
type LinkRow={work_orders_project_id:string;irrigation_project_id:string;irrigation_project_name:string|null;last_synced_at:string|null};
type SiteStats={total:number;synced:number;inactive:number};
type Summary={sites:number;syncedSites:number;inactiveSites:number;failedImports:number};
const emptySummary:Summary={sites:0,syncedSites:0,inactiveSites:0,failedImports:0};
const syncAge=(value:string|null)=>value?Math.floor((Date.now()-new Date(value).getTime())/86400000):null;

export default function AdminPage(){
 const [workProjects,setWorkProjects]=useState<BasicProject[]>([]),[irrigationProjects,setIrrigationProjects]=useState<BasicProject[]>([]),[links,setLinks]=useState<LinkRow[]>([]),[siteStats,setSiteStats]=useState<Record<string,SiteStats>>({}),[summary,setSummary]=useState<Summary>(emptySummary);
 const [selections,setSelections]=useState<Record<string,string>>({}),[loading,setLoading]=useState(true),[busyId,setBusyId]=useState(''),[message,setMessage]=useState(''),[messageTone,setMessageTone]=useState<'success'|'error'>('success'),[query,setQuery]=useState(''),[filter,setFilter]=useState<'all'|'linked'|'unlinked'|'stale'>('all');
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setMessage('');try{const response=await fetch(`/api/irrigation/projects?t=${Date.now()}`,{cache:'no-store',headers:{'Cache-Control':'no-cache'}});const data=await response.json();if(!response.ok)throw new Error(data.error||'تعذر تحميل بيانات النظام.');const projects:BasicProject[]=data.workProjects||[];const projectIds=new Set(projects.map(project=>project.id));const activeLinks:LinkRow[]=(data.links||[]).filter((link:LinkRow)=>projectIds.has(link.work_orders_project_id));setWorkProjects(projects);setIrrigationProjects(data.irrigationProjects||[]);setLinks(activeLinks);setSiteStats(data.projectSiteStats||{});setSummary(projects.length?data.summary||emptySummary:emptySummary);const next:Record<string,string>={};for(const link of activeLinks)next[link.work_orders_project_id]=link.irrigation_project_id;setSelections(next)}catch(error){setMessageTone('error');setMessage(error instanceof Error?error.message:'تعذر تحميل بيانات النظام.')}finally{setLoading(false)}}
 const linkMap=useMemo(()=>new Map(links.map(link=>[link.work_orders_project_id,link])),[links]);
 const linkedCount=links.length,unlinkedCount=Math.max(0,workProjects.length-linkedCount),staleCount=links.filter(link=>syncAge(link.last_synced_at)===null||(syncAge(link.last_synced_at)??0)>1).length;
 const hasProjects=workProjects.length>0;
 const healthScore=hasProjects?Math.round((linkedCount/workProjects.length)*100):0;
 const filtered=useMemo(()=>workProjects.filter(project=>{const link=linkMap.get(project.id),age=syncAge(link?.last_synced_at||null),term=query.trim().toLowerCase();const matches=!term||`${project.name} ${project.contractor_name||''} ${link?.irrigation_project_name||''}`.toLowerCase().includes(term);const state=filter==='all'||(filter==='linked'&&!!link)||(filter==='unlinked'&&!link)||(filter==='stale'&&!!link&&(age===null||age>1));return matches&&state}),[workProjects,linkMap,query,filter]);
 async function saveAndSync(workProjectId:string){const irrigationProjectId=selections[workProjectId];if(!irrigationProjectId){setMessageTone('error');setMessage('اختر مشروع الري المقابل أولًا.');return}setBusyId(workProjectId);setMessage('');try{const linkResponse=await fetch('/api/irrigation/link',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workProjectId,irrigationProjectId})});const linkData=await safeJson(linkResponse,'حفظ الربط');if(!linkResponse.ok)throw new Error(linkData.error||`تعذر حفظ الربط (${linkResponse.status}).`);const syncResponse=await fetch('/api/irrigation/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workProjectId})});const syncData=await safeJson(syncResponse,'مزامنة المواقع');if(!syncResponse.ok)throw new Error(syncData.error||`تم حفظ الربط، لكن تعذرت المزامنة (${syncResponse.status}).`);await load();setMessageTone('success');setMessage(`تم الربط ومزامنة ${syncData.synced??0} موقع بنجاح${syncData.deactivated?`، وتعطيل ${syncData.deactivated} موقع قديم`:''}.`)}catch(error){setMessageTone('error');setMessage(error instanceof Error?error.message:'حدث خطأ أثناء الربط والمزامنة.')}finally{setBusyId('')}}
 return <main className="module-page system-admin-page">
  <section className="admin-hero"><div><span className="eyebrow">التحكم والتكاملات</span><h1>إدارة النظام</h1><p>راقب ربط مشروع النظام بمشروع الري، ثم تابع حداثة مزامنة المواقع بشكل مستقل.</p><div className="admin-health-line"><i className={!hasProjects?'neutral':unlinkedCount?'danger':staleCount?'warning':'good'}/><span>{loading?'جاري فحص النظام...':!hasProjects?'لا توجد مشاريع مسجلة في النظام':unlinkedCount?'يوجد مشروع غير مربوط':staleCount?'الربط مكتمل، والمزامنة تحتاج تحديثًا':'الربط والمزامنة مكتملان'}</span></div></div><div className="admin-health-score"><small>اكتمال الربط</small><strong>{healthScore}%</strong><span>{hasProjects?`${linkedCount} من ${workProjects.length} مشاريع مرتبطة`:'لا يوجد مشروع للربط'}</span></div></section>
  {message?<div className={`admin-message ${messageTone}`}>{message}</div>:null}
  <section className="admin-stats"><div><small>مشروع النظام</small><strong>{workProjects.length}</strong><span>{workProjects.length===1?'المشروع الفعلي المسجل حاليًا':'المشاريع الفعلية المسجلة'}</span></div><div className={hasProjects&&!unlinkedCount?'success':''}><small>حالة الربط</small><strong>{linkedCount}/{workProjects.length}</strong><span>{!hasProjects?'لا يوجد مشروع للربط':unlinkedCount?'يوجد مشروع يحتاج ربطًا':'كل المشاريع مرتبطة'}</span></div><div><small>المواقع المسجلة</small><strong>{summary.sites}</strong><span>{summary.syncedSites} من نظام الري · {Math.max(0,summary.sites-summary.syncedSites)} محلية</span></div><div className={hasProjects?(staleCount?'danger':'success'):''}><small>حالة المزامنة</small><strong>{!hasProjects?'لا توجد بيانات':staleCount?'تحتاج تحديث':'حديثة'}</strong><span>{!hasProjects?'تبدأ بعد إضافة مشروع وربطه':staleCount?'آخر مزامنة أقدم من 24 ساعة':'تمت المزامنة خلال آخر 24 ساعة'}</span></div></section>
  <section className="admin-quick-grid"><Link href="/projects"><span>▦</span><div><strong>إدارة المشاريع</strong><small>إضافة وتعديل وأرشفة المشاريع</small></div></Link><Link href="/sites"><span>⌖</span><div><strong>إدارة المواقع</strong><small>مراجعة المواقع المتزامنة وحالاتها</small></div></Link><Link href="/alerts"><span>!</span><div><strong>مركز التنبيهات</strong><small>متابعة الأخطاء والمواعيد الحرجة</small></div></Link></section>
  <section className="admin-integration-panel"><header><div><span className="section-kicker">تكامل نظام الري</span><h2>ربط المشاريع ومزامنة المواقع</h2><p>المصدر: نظام الري والحدائق ← الوجهة: مرجع أوامر العمل والمواقع</p></div><b>{workProjects.length} مشروع</b></header>{loading?<div className="admin-loading"><span/><span/><span/></div>:!hasProjects?<div className="admin-empty-state"><span>▦</span><h3>لا توجد مشاريع لربطها</h3><p>أضف مشروعًا جديدًا أولًا، وبعدها سيظهر هنا لاختيار مشروع الري المقابل ومزامنة المواقع.</p><Link href="/projects">فتح إدارة المشاريع</Link></div>:<div className="admin-project-list">{workProjects.map(project=>{const linked=linkMap.get(project.id),stats=siteStats[project.id]||{total:0,synced:0,inactive:0},age=syncAge(linked?.last_synced_at||null);return <article className={`admin-project-row ${linked?'is-linked':'is-unlinked'} ${linked&&(age===null||age>1)?'is-stale':''}`} key={project.id}><div className="admin-project-name"><span>{linked?'✓':'!'}</span><div><small>مشروع أوامر العمل</small><strong>{project.name}</strong><p>{project.contractor_name||'المقاول غير مسجل'}</p></div></div><label><small>المشروع المقابل في نظام الري</small><select value={selections[project.id]||''} onChange={event=>setSelections(current=>({...current,[project.id]:event.target.value}))}><option value="">اختر مشروع الري...</option>{irrigationProjects.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><div className="admin-project-metrics"><span><small>المواقع</small><b>{stats.total}</b></span><span><small>متزامنة</small><b>{stats.synced}</b></span><span><small>غير نشطة</small><b>{stats.inactive}</b></span></div><div className="admin-project-action"><span className={linked?'state linked':'state'}>{linked?'مربوط':'غير مربوط'}</span><small>{linked?.last_synced_at?`آخر مزامنة: ${new Date(linked.last_synced_at).toLocaleString('ar-SA')}`:'لم تتم المزامنة بعد'}</small><button type="button" onClick={()=>void saveAndSync(project.id)} disabled={busyId===project.id}>{busyId===project.id?'جاري المزامنة...':linked?'حفظ ومزامنة':'ربط ومزامنة'}</button></div></article>})}</div>}</section>
 </main>
}

async function safeJson(response:Response,operation:string):Promise<{error?:string;synced?:number;deactivated?:number}>{const text=await response.text();try{return text?JSON.parse(text):{}}catch{throw new Error(`مسار ${operation} أعاد استجابة غير صحيحة (${response.status}).`)}}
